#!/bin/sh
###################################################################################################
#
#    @file   vte
#
#    @brief  shell script to mount the vte test suite for different platform from nfs 
#
###################################################################################################
#
#   Copyright (C) 2004, Freescale Semiconductor, Inc. All Rights Reserved
#   THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
#   BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
#   Freescale Semiconductor, Inc.
#
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author                          Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#Hake Huang/-----             20081007     N/A          Initial version
# 
###################################################################################################

TEST_SERVER=10.192.225.222

start_test()
{
TARGET=$(/mnt/nfs/tools/platfm.sh)
need_reboot=0
platfm=$(/mnt/nfs/tools/platfm.sh)
if [ -z "$TARGET" ]; then
return 1
fi
test_flag=$(cat /proc/cmdline | grep daily_test)
test_file=$(cat /proc/cmdline | sed 's/daily_test=/^/'| cut -d '^' -f 2 | cut -d " " -f 1)
if [ ! -z "$test_flag" ] && [ -e /mnt/nfs/vte_${TARGET}_d/runtest/${test_file} ]; then
 #enable watchdog here
 echo "start test in 30 seconds, or login then kill the test"
 sleep 30
 status=0
 while [ $status -eq 0 ]
 do
  sleep 30
  status=$(/mnt/nfs/tools/uclient 10.192.225.222 12500 ${platfm}_HELLO | grep ACK | wc -l)
	if [ $status -eq 0 ]; then
	  need_reboot=1
	fi
 done
 #chekc the uboot
 if [ $platfm = "IMX6-SABREAUTO" ]; then
 crc1=$(/mnt/nfs/tools/u-config_8k -g /dev/mmcblk0 | grep UVERSION | cut -d "=" -f 2)
 crc2=$(/mnt/nfs/tools/u-config_8k -g /root/u-boot-${platfm}-config.bin | grep UVERSION | cut -d "=" -f 2)
 else
 crc1=$(/mnt/nfs/tools/u-config -g /dev/mmcblk0 | grep UVERSION | cut -d "=" -f 2)
 crc2=$(/mnt/nfs/tools/u-config -g /root/u-boot-${platfm}-config.bin | grep UVERSION | cut -d "=" -f 2)
 fi
 if [ "$crc1" != "$crc2" ] && [ ! -z $crc1 ] && [ ! -z $crc2 ];then
  echo "need update uboot"
  dd if=/root/u-boot-${platfm}_d.bin of=/dev/mmcblk0 bs=1024 seek=1 skip=1
  dd if=/root/u-boot-${platfm}-config.bin of=/dev/mmcblk0 bs=1024 seek=768 count=256
  reboot
 fi
 if [ $need_reboot -eq 1 ]; then
   reboot
 fi
 /mnt/nfs/tools/uclient 10.192.225.222 12500 ${platfm}_REGIST
 if [ $platfm = "IMX6-SABREAUTO" ]; then
 insmod /mnt/nfs/vte_${TARGET}_d/testcases/bin/imx2_wd_test.ko timer_margin=25
 else
 insmod /mnt/nfs/vte_${TARGET}_d/testcases/bin/mxc_wd_test.ko timer_margin=25
 fi
 export CONTINUE=y
 tstatus=$(/mnt/nfs/tools/uclient 10.192.225.222 12500 ${platfm}_HELLO | grep ACK | wc -l)
 if [ $tstatus -gt 0 ]; then
  cd /mnt/nfs/vte_${TARGET}_d && /mnt/nfs/vte_${TARGET}_d/mytest $test_file
  #test finished start a process to reset board at
  /mnt/nfs/tools/uclient 10.192.225.222 12500 ${platfm}_TESTEND &
 fi
 while true;
 do
  sleep 1800;
#if no command can execute guess the rootfs is changed then reboot
	ls / || reboot
  kver=$(/mnt/nfs/tools/uclient 10.192.225.222 12500 ${platfm}_HELLO | grep KVER | cut -f 5 -d " ")
	kh=$(uname -r | cut -d - -f 1)
	if [ $(uname -r) !=  $kh$kver ]; then
#kernel changed restart test
  	status=$(/mnt/nfs/tools/uclient 10.192.225.222 12500 ${platfm}_HELLO | grep ACK | wc -l)
		if [ $status -eq 1 ];then
    	reboot
		fi
	fi
 done
fi
}

if [ $1 != "start" ]; then
 echo "say goodby"
 exit
fi

mount -t nfs -o nolock,tcp,rsize=1024,wsize=1024 ${TEST_SERVER}:/rootfs/wb /mnt/nfs
#check time
if [ $? -ne 0 ]; then
 echo "mount test nfs failure..."
 exit
fi
sleep 1
echo $(hostname -i) > /root/.mounts
/mnt/nfs/util/ntpdate 10.192.225.222
/sbin/hwclock -w
sleep 1
#/mnt/nfs/vte_${TARGET}/mytest
start_test
